name: gnn-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - scikit-learn
  - pytorch
  - networkx
  - pip:
      - torch-geometric
      - azure-ai-ml
      - azure-identity
      - python-dotenv
      - xlrd
      - openpyxl
